package dk.easv.belman.GUI;

import dk.easv.belman.BE.Cut;
import dk.easv.belman.BE.Item;
import dk.easv.belman.BE.ItemList;
import dk.easv.belman.BE.Operator;
import dk.easv.belman.BE.ProductionOrder;
import dk.easv.belman.BE.SalesOrder;
import dk.easv.belman.BE.SalesOrderList;
import dk.easv.belman.BE.StockItem;
import dk.easv.belman.BE.StockItemList;
import dk.easv.belman.BLL.Filter;
import dk.easv.belman.BLL.ListManager;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.SortOrder;
import org.jdesktop.swingx.JXTable;

public class MainGui extends javax.swing.JFrame {

    // Sleeve/Item table and it's model.
    private JXTable tblSleeves;
    private SleeveTableModel sleeveModel;
    // Currently selected Item/Sleeve from the table.
    private Item selectedItem;
    // A cut that will be added to the history after pressing done
    private Cut cut;
    // Currently selected operator
    private Operator operator;
    // Stock table and it's model.
    private JXTable tblStock;
    private StockTableModel stockModel;
    // Currently selected StockItem from the table.
    private StockItem selectedStockItem;
    // BLL object.
    private Filter filter;
    private ListManager listManager;
    // Timers for calculating time for each cut;
    private Date startTime;
    private Date endTime;

    /**
     * Constructor for the Main Form.
     */
    public MainGui() {
        initComponents(); // Initialize the components created by the NetBeans Designer.
        init(); // Initialize all the other components and variables created by us.
    }

    /**
     * @TODO JavaDOC
     * @param showUrgentPopup
     */
    public void scheduledUpdate(boolean showUrgentPopup) {
        if (showUrgentPopup) {
            JOptionPane.showMessageDialog(null, "There is a new Ugent order!", "Ugent order", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Initializes the components that were not generated by the NetBeans
     * Designer.
     */
    private void init() {
        // BLL object for the filtering.
        filter = new Filter();
        listManager = new ListManager();

        // Initializes the DescriptionPane and hides the components by default.
        setVisibleTo(false, lblDescriptionText1, lblDescriptionText2,
                lblDescriptionText3, lblDescriptiontext4, lblDescriptionText5,
                lblDescriptionText6, lblDescriptionText7, txtDescription1,
                txtDescription2, txtDescription3, txtDescription4,
                txtDescription5, txtDescription6, txtDescription7);

        // Sleeve table
        tblSleeves = new JXTable(); // Creates an empty JXTable (from SwingX 1.6.1) for now.
        JScrollPane sp = new JScrollPane(tblSleeves); // Creates a Scroll Pane where the table will be.
        sleeveModel = new SleeveTableModel(getAllSalesOrderNotDone()); // Initializes the SleeveTableModel.
        tblSleeves.setModel(sleeveModel); // Sets the table model.
        tblSleeves.setDragEnabled(false); // Dragging is disabled.
        tblSleeves.setColumnControlVisible(true); // Column control settings are enabled.
        tblSleeves.packAll(); // Packs the table.
        tblSleeves.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Only one selection is allowed per table.
        tblSleeves.setSortable(false);

        pnlCenter.setLayout(new BorderLayout()); // Sets the layout for the center JPanel.
        pnlCenter.add(sp); // Adds the Scroll Pane with the table to the JPanel on the center.
        addListeners(tblSleeves); // Add key and click listeners.

        // Stock table
        tblStock = new JXTable(); // Creates an empty JXTable (from SwingX 1.6.1) for now.
        JScrollPane sf = new JScrollPane(tblStock); // Creates a Scroll Pane where the table will be.
        stockModel = new StockTableModel(Main.allStockData); // Initializes the StockTableModel.
        tblStock.setModel(stockModel); // Sets the table model.
        tblSleeves.setDragEnabled(false); // Dragging is disabled.
        tblStock.setColumnControlVisible(true); // Column control settings are enabled.
        tblStock.packAll(); // Packs the table.
        tblStock.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Only one selection is allowed per table.
        tblStock.setSortable(false);

        pnlWest.setLayout(new BorderLayout()); // Sets the layout for the west JPanel.
        pnlWest.add(sf); // Adds the Scroll Pane with the table to the JPanel on the west.
        addListeners(tblStock); // Add key and click listeners.

        // Populate OperatorComboBox on the jpCut
        pupulateOperatorComboBox();


    }

    /**
     * This method populates the cmbbxOperator with the Operators that do exist
     * in the database.
     */
    private void pupulateOperatorComboBox() {
        DefaultComboBoxModel operatorModel = new DefaultComboBoxModel();
        for (Operator op : Main.allOperatorData.getList()) {
            operatorModel.addElement(op);
        }
        cmbbxOperator.setModel(operatorModel);
    }

    /**
     * Adds Mouse- and KeyListener to the specified table.
     *
     * @param c The component to which the ActionListeners will be added.
     */
    private void addListeners(final JXTable c) {
        // Start of the MouseListener.
        c.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // In case of any clicks...
                if (e.getSource().equals(tblSleeves)) {
                    tblStock.clearSelection(); // Clear the selection.
                    selectedItem = sleeveModel.getItemByRow(tblSleeves.getSelectedRow()); // Set the new selection.
                } else {
                    tblSleeves.clearSelection(); // Clear the selection.
                    selectedStockItem = stockModel.getStockByRow(tblStock.getSelectedRow()); // Set the new selection.

                }

                if (e.getClickCount() != 2) { // In case of a single click...
                    if (e.getSource().equals(tblSleeves)) {
                        setItemDescriptionPane(selectedItem); // Show information about the selected Item/Sleeve in the DescriptionPane.
                    } else {
                        setStockDescriptionPane(selectedStockItem); // Show information about the selected StockItem in the DescriptionPane.
                    }
                } else { // In case of a double click...

                    if (e.getSource().equals(tblSleeves)) {
                        selectedItem = sleeveModel.getItemByRow(tblSleeves.getSelectedRow()); // Set the selected Item/Sleeve.
                        // Filter the table with StockItems, by the currently selected Item/Sleeve.
                        updateStockTableModel(filter.filterBySleeve(Main.allStockData, selectedItem));

                        // Set the selected Item/Sleeve ready-to-cut.
                        txtSleeve.setText(sleeveModel.getValueAt(tblSleeves.getSelectedRow(), 0).toString());
                        txtQuantity.setText(String.valueOf(listManager.getRemaningCuts(Main.allCuts, selectedItem)));
                    } else {
                        selectedStockItem = stockModel.getStockByRow(tblStock.getSelectedRow()); // Set the selected StockItem.
                        // Filter the table with Items/Sleeves, by the currently selected StockItem.
                        updateSleeveTableModel(null, filter.filterByStock(getAllSalesOrderNotDone(), selectedStockItem));
                        // Set the selected StockItem ready-to-cut.
                        txtStockItem.setText(selectedStockItem.getCode());
                    }
                    setCutAmount();
                }

            }
        });
        // End of the MouseListener.
        // Start of the KeyListener.
        c.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                int keyUp = KeyEvent.VK_UP; // UP (arrow) key code.
                int keyDown = KeyEvent.VK_DOWN; // DOWN (arrow) key code.
                int keyEnter = KeyEvent.VK_ENTER; // ENTER key code.

                if (e.getKeyCode() == keyUp) { // If the UP key is pressed...
                    if (e.getSource().equals(tblSleeves)) {
                        selectedItem = sleeveModel.getItemByRow(tblSleeves.getSelectedRow() - 1); // Move the selection up.
                        setItemDescriptionPane(selectedItem); // Show information about the selected Item/Sleeve in the DescriptionPane.
                    } else {
                        selectedStockItem = stockModel.getStockByRow(tblStock.getSelectedRow() - 1); // Move the selection up.
                        setStockDescriptionPane(selectedStockItem); // Show information about the selected StockItem in the DescriptionPane.
                    }
                } else if (e.getKeyCode() == keyDown) { // If the DOWN key is pressed...
                    if (e.getSource().equals(tblSleeves)) {
                        selectedItem = sleeveModel.getItemByRow(tblSleeves.getSelectedRow() + 1); // Move the selection down.
                        setItemDescriptionPane(selectedItem); // Show information about the selected Item/Sleeve in the DescriptionPane.
                    } else {
                        selectedStockItem = stockModel.getStockByRow(tblStock.getSelectedRow() + 1); // Move the selection down.
                        setStockDescriptionPane(selectedStockItem); // Show information about the selected StockItem in the DescriptionPane.
                    }
                } else if (e.getKeyCode() == keyEnter) { // If the ENTER key is pressed...
                    if (e.getSource().equals(tblSleeves)) { // Set the selected Item/Sleeve ready-to-cut.
                        txtSleeve.setText(sleeveModel.getValueAt(tblSleeves.getSelectedRow(), 0).toString());
                        txtQuantity.setText(String.valueOf(listManager.getRemaningCuts(Main.allCuts, selectedItem)));
                    } else { // Set the selected StockItem ready-to-cut.
                        txtStockItem.setText(selectedStockItem.getCode());
                    }
                }
            }
        });
    }

    /**
     * @TODO JAVADOC!!!!!!!!!!
     */
    private void setCutAmount() {
        if (selectedItem != null && selectedStockItem != null) {
            if (filter.canCut(selectedStockItem, selectedItem)) {
                int cutAmount = filter.canCutHowMany(selectedStockItem, selectedItem); // Gets the actual amount possible to cut
                if (cutAmount > listManager.getRemaningCuts(Main.allCuts, selectedItem)) { // Checks if the possible amount is greater than the quantity needed
                    txtCutAmount.setText(String.valueOf(listManager.getRemaningCuts(Main.allCuts, selectedItem))); // In case possible amount is greater, set the amount to the needed amount
                } else {
                    txtCutAmount.setText(String.valueOf(cutAmount)); // In case possible amount is less, set the amount to the possible amount
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEast = new javax.swing.JSplitPane();
        jpDescription = new javax.swing.JPanel();
        lblDescription = new javax.swing.JLabel();
        lblDescriptionText1 = new javax.swing.JLabel();
        lblDescriptionText2 = new javax.swing.JLabel();
        lblDescriptionText3 = new javax.swing.JLabel();
        lblDescriptiontext4 = new javax.swing.JLabel();
        txtDescription1 = new javax.swing.JTextField();
        txtDescription2 = new javax.swing.JTextField();
        txtDescription3 = new javax.swing.JTextField();
        txtDescription4 = new javax.swing.JTextField();
        lblDescriptionText5 = new javax.swing.JLabel();
        txtDescription5 = new javax.swing.JTextField();
        lblDescriptionText6 = new javax.swing.JLabel();
        txtDescription6 = new javax.swing.JTextField();
        txtDescription7 = new javax.swing.JTextField();
        lblDescriptionText7 = new javax.swing.JLabel();
        jpCut = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSleeve = new javax.swing.JTextField();
        txtStockItem = new javax.swing.JTextField();
        cmbbxOperator = new javax.swing.JComboBox();
        btnCutAction = new javax.swing.JButton();
        txtCutAmount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        pnlHeader = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        pnlWest = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbbxWeekLimit = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1000, 650));
        setPreferredSize(new java.awt.Dimension(1000, 650));

        pnlEast.setDividerLocation(325);
        pnlEast.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        pnlEast.setPreferredSize(new java.awt.Dimension(325, 650));

        jpDescription.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        lblDescription.setText("Description");

        lblDescriptionText1.setText("Text");

        lblDescriptionText2.setText("Text");

        lblDescriptionText3.setText("Text");

        lblDescriptiontext4.setText("Text");

        lblDescriptionText5.setText("Text");

        lblDescriptionText6.setText("Text");

        lblDescriptionText7.setText("Text");

        javax.swing.GroupLayout jpDescriptionLayout = new javax.swing.GroupLayout(jpDescription);
        jpDescription.setLayout(jpDescriptionLayout);
        jpDescriptionLayout.setHorizontalGroup(
            jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescriptionText1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescriptionText2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(txtDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescriptionText3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescriptiontext4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescription4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescriptionText5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescription5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescription)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescriptionText6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescription6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDescriptionLayout.createSequentialGroup()
                        .addComponent(lblDescriptionText7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(txtDescription7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpDescriptionLayout.setVerticalGroup(
            jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDescription)
                .addGap(18, 18, 18)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptionText1)
                    .addComponent(txtDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptionText2)
                    .addComponent(txtDescription2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptionText3)
                    .addComponent(txtDescription3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptiontext4)
                    .addComponent(txtDescription4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptionText5)
                    .addComponent(txtDescription5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptionText6)
                    .addComponent(txtDescription6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpDescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescriptionText7)
                    .addComponent(txtDescription7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pnlEast.setTopComponent(jpDescription);

        jpCut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        jpCut.setForeground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Operator");

        jLabel3.setText("Selected Sleeve:");

        jLabel4.setText("Selected Stock Item: ");

        jLabel5.setText("Amount to cut");

        jLabel7.setText("Cutting handler");

        txtSleeve.setEditable(false);

        txtStockItem.setEditable(false);

        btnCutAction.setText("Start");
        btnCutAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCutActionActionPerformed(evt);
            }
        });

        txtCutAmount.setEditable(false);

        jLabel6.setText("Actual cut amount");

        txtQuantity.setEditable(false);

        javax.swing.GroupLayout jpCutLayout = new javax.swing.GroupLayout(jpCut);
        jpCut.setLayout(jpCutLayout);
        jpCutLayout.setHorizontalGroup(
            jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCutLayout.createSequentialGroup()
                        .addComponent(btnCutAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jpCutLayout.createSequentialGroup()
                        .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCutLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(txtStockItem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCutLayout.createSequentialGroup()
                                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSleeve, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                    .addComponent(cmbbxOperator, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCutLayout.createSequentialGroup()
                                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCutAmount, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))))
                        .addGap(10, 10, 10))
                    .addGroup(jpCutLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpCutLayout.setVerticalGroup(
            jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(12, 12, 12)
                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbbxOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSleeve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtStockItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpCutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCutAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnCutAction, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pnlEast.setRightComponent(jpCut);

        pnlHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        txtID.setToolTipText("Enter RP-Code / SO or PO's ID or Description");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnHistory.setText("Cut history");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHistory)
                .addContainerGap())
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK)
                    .addComponent(btnHistory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pnlCenter.setPreferredSize(new java.awt.Dimension(400, 0));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlWest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pnlWest.setPreferredSize(new java.awt.Dimension(400, 862));

        javax.swing.GroupLayout pnlWestLayout = new javax.swing.GroupLayout(pnlWest);
        pnlWest.setLayout(pnlWestLayout);
        pnlWestLayout.setHorizontalGroup(
            pnlWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        pnlWestLayout.setVerticalGroup(
            pnlWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 813, Short.MAX_VALUE)
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(25, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("Sleeve");

        jLabel8.setText("Stock Item");

        cmbbxWeekLimit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Show all", "1 week", "2 week", "3 week", "4 week" }));
        cmbbxWeekLimit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbxWeekLimitActionPerformed(evt);
            }
        });

        jLabel9.setText("List all within(weeks)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlWest, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbbxWeekLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addComponent(pnlEast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(cmbbxWeekLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                            .addComponent(pnlWest, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                            .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlEast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @TODO JavaDOC
     * @param evt
     */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (txtID.getText().isEmpty()) {
            updateSleeveTableModel(getAllSalesOrderNotDone(), null);
            updateStockTableModel(Main.allStockData);
        } else {
            SalesOrderList sol = new SalesOrderList();
            StockItemList sil = new StockItemList();

            boolean hasFound = false;

            while (!hasFound) {
                if (txtID.getText().startsWith("RP")) {
                    for (StockItem s : Main.allStockData.getList()) {
                        if (s.getCode().contains(txtID.getText())) {
                            sil.add(s);
                        }
                        hasFound = true;
                    }
                } else {
                    for (SalesOrder s : getAllSalesOrderNotDone().getList()) {
                        if (s.getDescription().contains(txtID.getText()) || String.valueOf(s.getId()).contains(txtID.getText())) {
                            if (!sol.hasId(s.getId())) {
                                sol.add(s);
                            }

                            hasFound = true;
                        }
                        for (ProductionOrder p : s.getProductOrderList().getList()) {
                            if (p.getDescription().contains(txtID.getText()) || String.valueOf(p.getId()).contains(txtID.getText())) {
                                if (!sol.hasId(s.getId())) {
                                    sol.add(s);
                                }

                                hasFound = true;

                            }
                        }
                    }
                    if (!hasFound) {
                        JOptionPane.showMessageDialog(this, "Nothing was found from your query", "Nothing found", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                }
            }
            if (hasFound) {
                if (sol.size() > 0) {
                    updateSleeveTableModel(sol, null);
                } else {
                    updateStockTableModel(sil);
                }
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void cmbbxWeekLimitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbxWeekLimitActionPerformed
        int weeks;
        switch (cmbbxWeekLimit.getSelectedIndex()) {
            case 0: // In case of 'View all' is selected...
                updateSleeveTableModel(getAllSalesOrderNotDone(), null); // Set back the original SalesOrderList.
                System.out.println("current size: " + sleeveModel.getSList().size() + "\n\n");
                break;
            case 1: // In case '1 week' is selected.
                weeks = 1;
                updateSleeveTableModel(filter.getSalesOrderList(getAllSalesOrderNotDone(), weeks), null);
                System.out.println("current size: " + sleeveModel.getSList().size() + "\n\n");
                break;
            case 2: // In case '2 week' is selected.
                weeks = 2;
                updateSleeveTableModel(filter.getSalesOrderList(getAllSalesOrderNotDone(), weeks), null);
                System.out.println("current size: " + sleeveModel.getSList().size() + "\n\n");
                break;
            case 3: // In case '3 week' is selected.
                weeks = 3;
                updateSleeveTableModel(filter.getSalesOrderList(getAllSalesOrderNotDone(), weeks), null);
                System.out.println("current size: " + sleeveModel.getSList().size() + "\n\n");
                break;
            case 4: // In case '4 week' is selected.
                weeks = 4;
                updateSleeveTableModel(filter.getSalesOrderList(getAllSalesOrderNotDone(), weeks), null);
                System.out.println("current size: " + sleeveModel.getSList().size() + "\n\n");
                break;
        }
    }//GEN-LAST:event_cmbbxWeekLimitActionPerformed

    private void btnCutActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCutActionActionPerformed
        if (txtStockItem.getText().length() > 0 &&// Makes sure stock item has been set
                txtSleeve.getText().length() > 0)// Makes sure that sleeve has been set
        {

            if (btnCutAction.getText().equals("Start")) {
                startTime = new Date(); // Sets a start time for tracking the time for the cut
                System.out.println("You started cutting");
                btnCutAction.setText("Stop");
                //System.out.println("SOL SIZE: " + getAllDoneSalesOrder().size());


            } else {
                endTime = new Date(); // Sets a end time for tracking the time for the cut
                long time = endTime.getTime() - startTime.getTime(); // Is the time it took for the cut to finish
                System.out.println("You stopped cutting");
                btnCutAction.setText("Start");

                System.out.println("Before: " + Main.allCuts.size());
                
                Cut cut = new Cut();
                cut.setSleeve(selectedItem);
                cut.setStockItem(selectedStockItem);
                cut.setOperator((Operator) cmbbxOperator.getSelectedItem());
                cut.setTimeSpent(time);
                Date currentDate = new Date();
                cut.setDate(currentDate.getTime());
                cut.setQuantity(Integer.valueOf(txtCutAmount.getText()));
                
                Main.allCuts.add(cut);
                System.out.println("After: " + Main.allCuts.size());

                txtQuantity.setText(String.valueOf(listManager.getRemaningCuts(Main.allCuts, selectedItem)));
                setCutAmount();
                listManager.insertCut(cut);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please make sure that values are set", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCutActionActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        CutHistoryFrame chf = new CutHistoryFrame(this);
    }//GEN-LAST:event_btnHistoryActionPerformed
    /**
     * Returns a sales order list containing all sales order which is not done
     *
     * @return
     */
    private SalesOrderList getAllSalesOrderNotDone() {
        return listManager.getAllSalesOrderNotDone(Main.allOrderData);
    }

//    /**
//     * Returns a sales order list containing all sales order which is done
//     *
//     * @return
//     */
//    private SalesOrderList getAllDoneSalesOrder() {
//        //return listManager.getAllDoneSalesOrder(Main.allOrderData);
//    }
    /**
     * Sets a new SalesOrderList or ItemList to the sleeve table. Incase sol is
     * null, it will set a new ItemList and vice versa.
     *
     * @param sol The new SalesOrderList, iList The new ItemList
     */
    private void updateSleeveTableModel(SalesOrderList sol, ItemList iList) {
        if (sol != null) {
            sleeveModel.setItemList(sol);
        } else {
            sleeveModel.setItemList(iList);
        }
        sleeveModel.fireTableDataChanged();
    }

    /**
     * Sets a new StockItemList to the stock table.
     *
     * @param sol The new StockItemList.
     */
    private void updateStockTableModel(StockItemList sil) {
        stockModel.setStockList(sil);
        stockModel.fireTableDataChanged();
    }

    /**
     * Fires the data changes to the table when this method is called.
     *
     */
    public void fireSleeveTableChanges() {
        sleeveModel.fireTableDataChanged();
    }

    /**
     * Sets up the DescriptionPane for a specified Item/Sleeve.
     *
     * @param item The selected Item/Sleeve.
     */
    public void setItemDescriptionPane(Item item) {
        // Un-hide the DescriptionPane's components.
        setVisibleTo(true, lblDescriptionText1, lblDescriptionText2,
                lblDescriptionText3, txtDescription1, txtDescription2,
                txtDescription3, lblDescriptiontext4, txtDescription4,
                lblDescriptionText5, txtDescription5, lblDescriptionText6,
                txtDescription6, lblDescriptionText7, txtDescription7);

        // Set the information.
        lblDescriptionText1.setText("SO ID / Description: ");
        txtDescription1.setText(item.getSalesOrderId() + " / " + getAllSalesOrderNotDone().getById(item.getSalesOrderId()).getDescription());
        lblDescriptionText2.setText("PO ID / Description: ");
        txtDescription2.setText(item.getProductOrderId() + " / " + listManager.getProductOrder(getAllSalesOrderNotDone(), selectedItem).getDescription());
        lblDescriptionText3.setText("Material ID: ");
        txtDescription3.setText(String.valueOf(item.getMaterialId()));
        lblDescriptiontext4.setText("Width: ");
        txtDescription4.setText(String.valueOf(item.getWidth()));
        lblDescriptionText5.setText("Circumference: ");
        txtDescription5.setText(String.valueOf(item.getCircumference()));
        lblDescriptionText6.setText("Thickness: ");
        txtDescription6.setText(String.valueOf(item.getThickness()));
        lblDescriptionText7.setText("Quantity: ");
//        txtDescription7.setText(String.valueOf(item.getQuantity())); @TODO

        // Set the DescriptionPane NOT editable.
        setEditableTo(false, txtDescription1, txtDescription2, txtDescription3,
                txtDescription4, txtDescription5, txtDescription6, txtDescription7);
    }

    /**
     * Sets up the DescriptionPane for a specified StockItem.
     *
     * @param item The selected StockItem.
     */
    private void setStockDescriptionPane(StockItem item) {
        // Un-hide the DescriptionPane's components.
        setVisibleTo(true, lblDescriptionText1, lblDescriptionText2,
                lblDescriptionText3, txtDescription1, txtDescription2,
                txtDescription3, lblDescriptiontext4, txtDescription4,
                lblDescriptionText5, txtDescription5, lblDescriptionText6,
                txtDescription6, lblDescriptionText7, txtDescription7);

        // Set the information.
        lblDescriptionText1.setText("Code:");
        txtDescription1.setText(item.getCode());
        lblDescriptionText2.setText("Material: ");
        txtDescription2.setText(String.valueOf(item.getMaterialId()) + " / " + item.getMaterialName());
        lblDescriptionText3.setText("Mat. Density");
        txtDescription3.setText(String.valueOf(item.getMaterialDensity()));
        lblDescriptiontext4.setText("Width: ");
        txtDescription4.setText(String.valueOf(item.getWidth()));
        lblDescriptionText5.setText("Length: ");
        txtDescription5.setText(String.valueOf(item.getLength()));
        lblDescriptionText6.setText("Thickness: ");
        txtDescription6.setText(String.valueOf(item.getThickness()));
        lblDescriptionText7.setText("Quantity(kg): ");
        txtDescription7.setText(String.valueOf(item.getQuantity()));

        // Set the DescriptionPane NOT editable.
        setEditableTo(false, txtDescription1, txtDescription2, txtDescription3,
                txtDescription4, txtDescription5, txtDescription6, txtDescription7);
    }

    /**
     * Takes in multiple Components and sets the visibility option for all.
     *
     * @param visibility A boolean.
     * @param comp All the components.
     */
    public void setVisibleTo(boolean visibility, Component... comp) {
        for (Component c : comp) {
            c.setVisible(visibility);
        }
    }

    /**
     * Takes in multiple JTextFields and sets the editable attribute for all.
     *
     * @param visibility A boolean.
     * @param comp All the components.
     */
    public void setEditableTo(boolean visibility, JTextField... comp) {
        for (JTextField c : comp) {
            c.setEditable(visibility);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCutAction;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cmbbxOperator;
    private javax.swing.JComboBox cmbbxWeekLimit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpCut;
    private javax.swing.JPanel jpDescription;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDescriptionText1;
    private javax.swing.JLabel lblDescriptionText2;
    private javax.swing.JLabel lblDescriptionText3;
    private javax.swing.JLabel lblDescriptionText5;
    private javax.swing.JLabel lblDescriptionText6;
    private javax.swing.JLabel lblDescriptionText7;
    private javax.swing.JLabel lblDescriptiontext4;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JSplitPane pnlEast;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlWest;
    private javax.swing.JTextField txtCutAmount;
    private javax.swing.JTextField txtDescription1;
    private javax.swing.JTextField txtDescription2;
    private javax.swing.JTextField txtDescription3;
    private javax.swing.JTextField txtDescription4;
    private javax.swing.JTextField txtDescription5;
    private javax.swing.JTextField txtDescription6;
    private javax.swing.JTextField txtDescription7;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSleeve;
    private javax.swing.JTextField txtStockItem;
    // End of variables declaration//GEN-END:variables
}
