package dk.easv.belman.GUI;

import dk.easv.belman.BE.Setting;
import dk.easv.belman.DAL.SettingsManager;
import java.awt.Color;

public class SettingsFrame extends javax.swing.JFrame {

    MainGui parent;

    /**
     * Creates new form SettingsFrame
     */
    public SettingsFrame(MainGui parent) {
        initComponents();
        this.parent = parent;
        this.setVisible(true); // Make the frame visible.
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblMinThickness = new javax.swing.JLabel();
        lblMaxThickness = new javax.swing.JLabel();
        jSpMinThickness = new javax.swing.JSpinner();
        jSpMaxThickness = new javax.swing.JSpinner();
        lblUrgentOrderColor = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnApply = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblRefreshPeriod = new javax.swing.JLabel();
        jSpRefreshPeriod = new javax.swing.JSpinner();
        lblUrgentOrders = new javax.swing.JLabel();
        jSpUrgentOrders = new javax.swing.JSpinner();
        lblExpiredOrderColor = new javax.swing.JLabel();
        lblRefreshPeriodMin = new javax.swing.JLabel();
        lblMinThicknessSec = new javax.swing.JLabel();
        lblMaxThicknessSec = new javax.swing.JLabel();
        lblUrgerntOrdersDay = new javax.swing.JLabel();
        btnUrgentColor = new javax.swing.JButton();
        btnExpiredColor = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMinThickness.setText("Time to cut a sleeve with 0.2 mm thickness:");

        lblMaxThickness.setText("Time to cut a sleeve with 0.8 mm thickness:");

        jSpMinThickness.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jSpMaxThickness.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        lblUrgentOrderColor.setText("Urgent order color:");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblRefreshPeriod.setText("Refresh period:");

        jSpRefreshPeriod.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        lblUrgentOrders.setText("Urgent order:");

        jSpUrgentOrders.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        lblExpiredOrderColor.setText("Expired order color:");

        lblRefreshPeriodMin.setText("minute(s)");

        lblMinThicknessSec.setText("second(s)");

        lblMaxThicknessSec.setText("second(s)");

        lblUrgerntOrdersDay.setText("day(s)");

        btnUrgentColor.setText("Select color");
        btnUrgentColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrgentColorActionPerformed(evt);
            }
        });

        btnExpiredColor.setText("Select color");
        btnExpiredColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 249, Short.MAX_VALUE)
                .addComponent(btnOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApply)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblMinThickness)
                        .addComponent(lblUrgentOrderColor)
                        .addComponent(lblRefreshPeriod)
                        .addComponent(lblUrgentOrders)
                        .addComponent(lblExpiredOrderColor))
                    .addComponent(lblMaxThickness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpMinThickness)
                            .addComponent(jSpMaxThickness)
                            .addComponent(jSpRefreshPeriod)
                            .addComponent(jSpUrgentOrders))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRefreshPeriodMin)
                            .addComponent(lblMinThicknessSec)
                            .addComponent(lblMaxThicknessSec)
                            .addComponent(lblUrgerntOrdersDay)))
                    .addComponent(btnUrgentColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExpiredColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnApply, btnCancel, btnOk});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnExpiredColor, btnUrgentColor, jSpMaxThickness, jSpMinThickness, jSpRefreshPeriod, jSpUrgentOrders});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRefreshPeriod)
                            .addComponent(lblRefreshPeriodMin))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSpRefreshPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMinThickness)
                    .addComponent(jSpMinThickness, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMinThicknessSec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaxThicknessSec)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpMaxThickness, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMaxThickness)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrgentOrders)
                    .addComponent(jSpUrgentOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUrgerntOrdersDay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUrgentOrderColor)
                    .addComponent(btnUrgentColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExpiredOrderColor)
                    .addComponent(btnExpiredColor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnApply)
                    .addComponent(btnCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnApply, btnCancel, btnOk});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnExpiredColor, btnUrgentColor, jSpMaxThickness, jSpMinThickness, jSpRefreshPeriod, jSpUrgentOrders});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUrgentColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrgentColorActionPerformed
        ColorChooserFrame colorChooser;
        colorChooser = new ColorChooserFrame(this, btnUrgentColor);
    }//GEN-LAST:event_btnUrgentColorActionPerformed

    private void btnExpiredColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredColorActionPerformed
        ColorChooserFrame colorChooser;
        colorChooser = new ColorChooserFrame(this, btnExpiredColor);
    }//GEN-LAST:event_btnExpiredColorActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        Main.settings.setRefreshPeriod((int) jSpRefreshPeriod.getValue());
        Main.settings.setLowestSeconds((int) jSpMinThickness.getValue());
        Main.settings.setHighestSeconds((int) jSpMaxThickness.getValue());
        Main.settings.setUrgentWithIn((int) jSpUrgentOrders.getValue());
        Main.settings.setExpiredColorRGB(btnExpiredColor.getBackground().getRGB());
        Main.settings.setUrgentColorRGB(btnUrgentColor.getBackground().getRGB());
        Main.settings.save();
        SettingsManager.applySettings();
        parent.btnSettings.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        parent.btnSettings.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
        Main.settings.setRefreshPeriod((int) jSpRefreshPeriod.getValue());
        Main.settings.setLowestSeconds((int)jSpMinThickness.getValue());
        Main.settings.setHighestSeconds((int) jSpMaxThickness.getValue());
        Main.settings.setUrgentWithIn((int) jSpUrgentOrders.getValue());
        Main.settings.setExpiredColorRGB(btnExpiredColor.getBackground().getRGB());
        Main.settings.setUrgentColorRGB(btnUrgentColor.getBackground().getRGB());
        Main.settings.save();
        SettingsManager.applySettings();
    }//GEN-LAST:event_btnApplyActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnExpiredColor;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnUrgentColor;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpMaxThickness;
    private javax.swing.JSpinner jSpMinThickness;
    private javax.swing.JSpinner jSpRefreshPeriod;
    private javax.swing.JSpinner jSpUrgentOrders;
    private javax.swing.JLabel lblExpiredOrderColor;
    private javax.swing.JLabel lblMaxThickness;
    private javax.swing.JLabel lblMaxThicknessSec;
    private javax.swing.JLabel lblMinThickness;
    private javax.swing.JLabel lblMinThicknessSec;
    private javax.swing.JLabel lblRefreshPeriod;
    private javax.swing.JLabel lblRefreshPeriodMin;
    private javax.swing.JLabel lblUrgentOrderColor;
    private javax.swing.JLabel lblUrgentOrders;
    private javax.swing.JLabel lblUrgerntOrdersDay;
    // End of variables declaration//GEN-END:variables

    private void init() {
        jSpRefreshPeriod.getModel().setValue(Main.settings.getRefreshPeriod());
        jSpMinThickness.getModel().setValue(Main.settings.getLowestSeconds());
        jSpMaxThickness.getModel().setValue(Main.settings.getHighestSeconds());
        jSpUrgentOrders.getModel().setValue(Main.settings.getUrgentWithIn());
        btnUrgentColor.setBackground(new Color(Main.settings.getUrgentColorRGB()));
        btnExpiredColor.setBackground(new Color(Main.settings.getExpiredColorRGB()));
    }
}
