/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dk.easv.belman.UI;

import java.awt.BorderLayout;
import javax.swing.JButton;

/**
 *
 * @author Dani
 */
public class MainGui extends javax.swing.JFrame {

    /**
     * Creates new form Belman
     */
    public MainGui() {
        initComponents();
        init();
    }

    private void init() {
        // Set Layouts to panels //
        
        // Set objects //
        OrderListing listing = new OrderListing(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnlWest = new javax.swing.JSplitPane();
        spnlCenter = new javax.swing.JSplitPane();
        spnlEast = new javax.swing.JSplitPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        spnlWest.setDividerLocation(400);
        spnlWest.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        spnlCenter.setDividerLocation(300);

        spnlEast.setDividerLocation(300);
        spnlEast.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        spnlCenter.setRightComponent(spnlEast);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(spnlWest, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnlWest, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(spnlCenter)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane spnlCenter;
    private javax.swing.JSplitPane spnlEast;
    private javax.swing.JSplitPane spnlWest;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the spnlCenter
     */
    public javax.swing.JSplitPane getSpnlCenter() {
        return spnlCenter;
    }

    /**
     * @return the spnlWest
     */
    public javax.swing.JSplitPane getSpnlWest() {
        return spnlWest;
    }

}
